ApplicationExceptionTest
Endpoint SingleSide;

SingleSide
{
    Public Function testApplicationException() returns TrueFalse
    {
        TrueFalse caught = False;
        try {
            1 / 0;
        }
        catch (ApplicationException as err) {
            caught = True;
        }
        return caught;
    }
}
