ApplicationExceptionCatcher
Endpoint Catcher;

Catcher
{
    Endpoint thrower;

    Public Function addEndpoint(Endpoint ref)
    {
        thrower = ref;
    }

    Public Function testCatchApplicationExceptionFromSequence() returns TrueFalse
    {
        TrueFalse caught = False;
        try {
            thrower.testPropagateException();
        }
        catch (ApplicationException as err) {
            caught = True;
        }
        return caught;
    }
}
