ExceptionPropagation
Endpoint Ping;
Endpoint Pong;

Sequences {
    testSequence: Ping.ping1 -> Pong.pong1 -> Ping.ping2 -> Pong.pong2;
}

Sequence testSequence(Number int) returns Number pingPongNum
{
    Ping.ping1
    {
        int += 1;
        terminate_pong();
    }
    Pong.pong1
    {
        int += 1;
    }
    Ping.ping2
    {
        int += 1;
    }
    Pong.pong2
    {
        int += 1;
        pingPongNum = int;
    }
}

Ping
{
    Function (in: Nothing; returns: Nothing) terminate_pong;

    Public Function addTerminationFunction(Function (in:Nothing; returns: Nothing) temp)
    {
        terminate_pong = temp;
    }

    Public Function testPropagateException()
    {
        testSequence(1); //propagate exception back out through endpoint call
    }
}

Pong
{
}
